language: rust
sudo: false
dist: trusty

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --no-default-features

env:
  global:
    - TRAVIS_RUST_VERSION="1.25.0